export const FETCH_SUCCESS = 'TASKINFO/FETCH_SUCCESS';
export const FETCH_FAILURE = 'TASKINFO/FETCH_FAILURE';
export const FETCH_STARTED = 'TASKINFO/FETCH_STARTED';
export const CLEAN_TASKINFO = 'TASKINFO/CLEAN_TASKINFO';