export const FETCH_SUCCESS = 'TASKPREVIEW/FETCH_SUCCESS';
export const FETCH_FAILURE = 'TASKPREVIEW/FETCH_FAILURE';
export const FETCH_STARTED = 'TASKPREVIEW/FETCH_STARTED';
export const CLEAN_TASKINFO = 'TASKPREVIEW/CLEAN_TASKINFO';